services:
  db:
    image: postgres:16
    container_name: edumind_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=edumind_db
      - POSTGRES_USER=edumind_user
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: edumind_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"  
    depends_on:
      - db

volumes:
  postgres_data: