# Generated by Django 5.2 on 2026-04-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0004_tentativaquiz_respostas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('tipo_prova', models.CharField(choices=[('ENADE', 'ENADE'), ('POSCOMP', 'POSCOMP')], max_length=10)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('quantidade_questoes', models.PositiveIntegerField()),
                ('tempo_total_segundos', models.PositiveIntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('questoes', models.ManyToManyField(blank=True, related_name='desafios', to='quizzes.questao')),
            ],
            options={
                'verbose_name': 'Desafio',
                'verbose_name_plural': 'Desafios',
                'ordering': ['tipo_prova', 'ordem'],
            },
        ),
    ]
