# Generated by Django 5.2 on 2026-05-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='nivel',
            field=models.PositiveIntegerField(choices=[(1, 'Fácil'), (2, 'Médio'), (3, 'Difícil')], default=1),
        ),
    ]
