# Generated by Django 5.2 on 2026-05-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0002_alter_desafio_nivel'),
        ('quizzes', '0007_questao_tipo_prova'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='desafio',
            constraint=models.UniqueConstraint(fields=('tipo_prova', 'ordem'), name='unique_desafio_tipo_prova_ordem'),
        ),
    ]
