# Generated by Django 5.2 on 2026-04-16 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('explicacao_resposta', models.TextField(blank=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='disciplinas.disciplina')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=1)),
                ('texto', models.CharField(max_length=255)),
                ('correta', models.BooleanField(default=False)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='quizzes.questao')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
                'ordering': ['questao', 'letra'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='disciplinas.disciplina')),
                ('questoes', models.ManyToManyField(blank=True, related_name='quizzes', to='quizzes.questao')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='TentativaQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_tentativa', models.DateTimeField(auto_now_add=True)),
                ('pontuacao', models.FloatField(default=0)),
                ('quantidade_acertos', models.PositiveIntegerField(default=0)),
                ('quantidade_erros', models.PositiveIntegerField(default=0)),
                ('percentual_acertos', models.FloatField(default=0)),
                ('desempenho_geral', models.CharField(blank=True, max_length=100)),
                ('tempo_gasto', models.DurationField(blank=True, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='quizzes.quiz')),
            ],
            options={
                'verbose_name': 'Tentativa de Quiz',
                'verbose_name_plural': 'Tentativas de Quiz',
                'ordering': ['-data_tentativa'],
            },
        ),
    ]
