# Generated by Django 5.2 on 2026-04-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='tipo_prova',
            field=models.CharField(choices=[('ENADE', 'ENADE'), ('POSCOMP', 'POSCOMP')], default='ENADE', max_length=10),
        ),
    ]
