# Generated by Django 5.2 on 2026-04-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz_tipo_prova'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativaquiz',
            name='respostas',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
