# Generated by Django 5.2 on 2026-04-29 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0001_initial'),
        ('quizzes', '0004_tentativaquiz_respostas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tentativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tentativa', models.CharField(choices=[('QUIZ', 'Quiz'), ('DESAFIO', 'Desafio')], max_length=10)),
                ('data_tentativa', models.DateTimeField(auto_now_add=True)),
                ('pontuacao', models.FloatField(default=0)),
                ('quantidade_acertos', models.PositiveIntegerField(default=0)),
                ('quantidade_erros', models.PositiveIntegerField(default=0)),
                ('percentual_acertos', models.FloatField(default=0)),
                ('desempenho_geral', models.CharField(blank=True, max_length=100)),
                ('tempo_gasto', models.DurationField(blank=True, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('aprovado', models.BooleanField(default=False)),
                ('respostas', models.JSONField(blank=True, default=dict)),
                ('desafio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_genericas', to='desafios.desafio')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_genericas', to='quizzes.quiz')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_genericas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentativa',
                'verbose_name_plural': 'Tentativas',
                'ordering': ['-data_tentativa'],
            },
        ),
        migrations.DeleteModel(
            name='TentativaQuiz',
        ),
    ]
