# Generated by Django 5.2 on 2026-04-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_tentativa_delete_tentativaquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='nivel_dificuldade',
            field=models.CharField(choices=[('FACIL', 'Fácil'), ('MEDIA', 'Média'), ('DIFICIL', 'Difícil')], default='MEDIA', max_length=10),
        ),
    ]
