# Generated by Django 5.2 on 2026-04-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_questao_nivel_dificuldade'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='tipo_prova',
            field=models.CharField(choices=[('ENADE', 'ENADE'), ('POSCOMP', 'POSCOMP'), ('AMBOS', 'Ambos')], default='AMBOS', max_length=10),
        ),
    ]
